version: '3.7'

services:
  cognihack-second-app:
    container_name: cognihack-second-app
    ports:
    - 8005:8000
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
  cognihack-redis-stack-server:
    container_name: cognihack-redis-stack-server
    restart: always
    ports:
      - 6375:6379
      - 8006:8001
    image: redis/redis-stack:latest # redis/redis-stack-server:latest for prod
    command: ["redis-server", "--requirepass", "redis-stack", "--loadmodule", "/opt/redis-stack/lib/redisearch.so", "--loadmodule", "/opt/redis-stack/lib/rejson.so"]
    volumes: 
      - cache:/data
      - redis:/var/lib/redis
volumes:
  cache:
    driver: local
  redis:
  
networks:
  default:
    name: cognihack-network
    external: true
    