version: '3.7'

services:
  cognihack-app:
    container_name: cognihack-app
    #image: webgrip/cognihack
    ports:
    - 1337:8000
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
  cognihack-redis-stack-server:
    container_name: cognihack-redis-stack-server
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    image: redis/redis-stack:latest # redis/redis-stack-server:latest for prod
    command: ["redis-server", "--requirepass", "redis-stack", "--loadmodule", "/var/redisearch.so", "--loadmodule", "/var/rejson.so"]

    environment:
    - REDIS_ARGS=""
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes: 
      - cache:/data
      - redis:/var/lib/redis
      - ./redis/modules/:/var
volumes:
  cache:
    driver: local
  redis: